kind: Deployment
apiVersion: apps/v1
metadata:
  name: livestats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livestats
  template:
    metadata:
      labels:
        app: livestats
    spec:
      containers:
        - image: quay.io/kennedn/livestats
          name: livestats
          ports:
            - containerPort: 5000
              protocol: TCP
